name: build shared library

on:
  push:
    branches: [ "*" ]


jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: init cmake
        run: cmake -S .

      - name: build shared library
        run: make

      - name: run gtest
        run: timeout 2m ./build/test-psar

