name: build shared library

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: init valgrind
        run: sudo apt-get install valgrind

      - name: init cmake
        run: cmake -S .

      - name: build shared library
        run: make

      - name: run main
        run: ./build/main-psar

      - name: run gtest
        run: timeout 2m valgrind --leak-check=full --show-leak-kinds=all make test


